version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: senapro-db
    restart: always
    environment:
      POSTGRES_USER: senapro
      POSTGRES_PASSWORD: senapro
      POSTGRES_DB: senapro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
