// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenaPro.Infrastructure.Data;

#nullable disable

namespace SenaPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenaPro.Domain.Entities.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acumulado")
                        .HasColumnType("boolean");

                    b.Property<int>("Concurso")
                        .HasColumnType("integer");

                    b.Property<bool>("Conferido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataProximoConcurso")
                        .HasColumnType("date");

                    b.Property<byte>("Dezena1")
                        .HasColumnType("smallint");

                    b.Property<byte>("Dezena2")
                        .HasColumnType("smallint");

                    b.Property<byte>("Dezena3")
                        .HasColumnType("smallint");

                    b.Property<byte>("Dezena4")
                        .HasColumnType("smallint");

                    b.Property<byte>("Dezena5")
                        .HasColumnType("smallint");

                    b.Property<byte>("Dezena6")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("DezenasOrdemSorteio")
                        .HasColumnType("bytea");

                    b.Property<int>("GanhadoresQuadra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GanhadoresQuina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GanhadoresSena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("LocalSorteio")
                        .HasColumnType("text");

                    b.Property<string>("MunicipioUFSorteio")
                        .HasColumnType("text");

                    b.Property<decimal?>("PremioQuadra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PremioQuina")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PremioSena")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ValorAcumuladoProximoConcurso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorArrecadado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorEstimadoProximoConcurso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Concurso")
                        .IsUnique();

                    b.ToTable("sorteios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
